name: Build for aarch64

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Push a tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        export NAME="yearly"
        git tag $NAME
        git push origin $NAME || echo "Tag exists already"
        
    - name: Setup rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
        chmod +x rustup-init.sh
        ./rustup-init.sh -y

    - name: Build bin
      run: |
        . $HOME/.cargo/env
        rustup target add aarch64-unknown-linux-musl

        sudo apt-get install -y \
          musl-tools \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          binutils-aarch64-linux-gnu \
          musl-dev

        export CC_aarch64_unknown_linux_musl=aarch64-linux-gnu-gcc
        export AR_aarch64_unknown_linux_musl=aarch64-linux-gnu-ar
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc

        cargo build --help
        printf "/n/n/n/n/n/"
        RUSTFLAGS="-C target-feature=-crt-static" cargo build \
        --target aarch64-unknown-linux-musl \
        --profile opt \
        --locked
        # --path helix-term \


    - name: Check
      run: |
        ls -lh
        printf "/n/n/n/n/n"
        tree target
        
        
