name: Build for aarch64

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Push a tag
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        export NAME="yearly"
        git tag $NAME
        git push origin $NAME || echo "Tag exists already"
        
    - name: Setup rust
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
        chmod +x rustup-init.sh
        ./rustup-init.sh -y

    - name: Build bin
      run: |
        . $HOME/.cargo/env
        rustup target add aarch64-unknown-linux-musl

        sudo apt-get update
        # DANGEROUS apt-cache search gcc
        sudo apt-get install -y \
          musl-tools \
          musl-dev \
          binutils-aarch64-linux-gnu
        # wget "http://musl.cc/aarch64-linux-musl-cross.tgz"
        # tar -xzf aarch64-linux-musl-cross.tgz -C /usr/local
        # export PATH=/usr/local/aarch64-linux-musl-cross/bin:$PATH
        curl -o zig.tar.xz "https://ziglang.org/download/0.15.1/zig-x86_64-linux-0.15.1.tar.xz"
        tar -xJf zig.tar.xz
        export PATH=$PWD/zig/bin:$PATH
        zig version

        export CC_aarch64_unknown_linux_musl="zig cc"
        export AR_aarch64_unknown_linux_musl="zig cc"
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER="zog cc"

        cargo build --help
        
        printf "




        "
        cargo install --help
        printf "





        "
        RUSTFLAGS="-C target-feature=-crt-static -C link-arg=-lm" cargo build \
        --target aarch64-unknown-linux-musl \
        --profile opt \
        --locked \
        -p helix-term


    - name: Check
      run: |
        ls -lh
        file target/aarch64-unknown-linux-musl/opt/hx
        printf "




        "
        tree target
        
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "yearly"
        draft: false
        files: |
          target/aarch64-unknown-linux-musl/opt/hx
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
